"""empty message

Revision ID: 204b23950497
Revises: 3b739a7b850c
Create Date: 2023-07-21 19:19:33.456227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204b23950497'
down_revision = '3b739a7b850c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['school'], ['stid'])

    # ### end Alembic commands ###
