"""empty message

Revision ID: 336d48f0a151
Revises: d999aeeb69d7
Create Date: 2023-07-21 19:31:31.068793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336d48f0a151'
down_revision = 'd999aeeb69d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['school'], ['stid'])

    # ### end Alembic commands ###
