"""empty message

Revision ID: 49b95701b656
Revises: aa5af19d677d
Create Date: 2023-07-21 20:03:55.103170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b95701b656'
down_revision = 'aa5af19d677d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('pk_stid_school_student', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('pk_stid_school_student', ['stid', 'school'])

    op.create_table('point',
    sa.Column('stid', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.INTEGER(), nullable=False),
    sa.Column('school', sa.TEXT(), nullable=False),
    sa.Column('local', sa.TEXT(), nullable=False),
    sa.Column('point', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['school'], ['student.stid'], ),
    sa.ForeignKeyConstraint(['stid'], ['student.stid'], ),
    sa.PrimaryKeyConstraint('stid', 'school'),
    sa.UniqueConstraint('stid', 'school', name='pk_stid_school_point')
    )
    # ### end Alembic commands ###
