"""empty message

Revision ID: 4df9e198ed1a
Revises: a87954b0924e
Create Date: 2023-07-21 13:39:21.188546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df9e198ed1a'
down_revision = 'a87954b0924e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accessor')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwd', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('passwd')

    op.create_table('accessor',
    sa.Column('stid', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.INTEGER(), nullable=False),
    sa.Column('school', sa.TEXT(), nullable=False),
    sa.Column('local', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['stid'], ['student.stid'], ),
    sa.PrimaryKeyConstraint('stid')
    )
    # ### end Alembic commands ###
