"""empty message

Revision ID: 532d0bfe6b6d
Revises: d19fe365bb1e
Create Date: 2023-07-21 19:15:46.107881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532d0bfe6b6d'
down_revision = 'd19fe365bb1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['school'], ['school'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['school'], ['stid'])

    # ### end Alembic commands ###
