"""empty message

Revision ID: 73f38ee5fdaf
Revises: 4df9e198ed1a
Create Date: 2023-07-21 13:48:41.629716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f38ee5fdaf'
down_revision = '4df9e198ed1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwd', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('passwd')

    # ### end Alembic commands ###
