"""empty message

Revision ID: 7aa686d04090
Revises: 73f38ee5fdaf
Create Date: 2023-07-21 17:40:28.880611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa686d04090'
down_revision = '73f38ee5fdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rival_school', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('rival_school')

    # ### end Alembic commands ###
