"""empty message

Revision ID: af6407bfa0c9
Revises: a4756cf8a78a
Create Date: 2023-07-21 19:14:25.409126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6407bfa0c9'
down_revision = 'a4756cf8a78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('pk_stid_school_student', ['stid', 'school'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('pk_stid_school_student', type_='unique')

    op.create_table('point',
    sa.Column('stid', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.INTEGER(), nullable=False),
    sa.Column('school', sa.TEXT(), nullable=False),
    sa.Column('local', sa.TEXT(), nullable=False),
    sa.Column('point', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stid'], ['student.stid'], ),
    sa.PrimaryKeyConstraint('stid')
    )
    # ### end Alembic commands ###
