"""empty message

Revision ID: b39357f9ca48
Revises: 49b95701b656
Create Date: 2023-07-21 20:04:36.957766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39357f9ca48'
down_revision = '49b95701b656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('stid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('school', sa.Text(), nullable=False),
    sa.Column('local', sa.Text(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stid', 'school', name='pk_stid_school_point2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    # ### end Alembic commands ###
