"""empty message

Revision ID: c868b4f48864
Revises: fc6115f9c65b
Create Date: 2023-07-21 19:55:26.800535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c868b4f48864'
down_revision = 'fc6115f9c65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_constraint('pk_stid_school_point', type_='unique')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('pk_stid_school_student', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('pk_stid_school_student', ['stid', 'school'])

    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['school'], ['stid'])
        batch_op.create_foreign_key(None, 'student', ['stid'], ['stid'])
        batch_op.create_unique_constraint('pk_stid_school_point', ['stid', 'school'])

    # ### end Alembic commands ###
