"""empty message

Revision ID: cd8f2e95db5f
Revises: 
Create Date: 2023-07-26 11:15:38.013813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8f2e95db5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Point',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('birth', sa.DateTime(), nullable=False),
    sa.Column('belong', sa.Text(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('local', sa.Text(), nullable=True),
    sa.Column('rival_id', sa.Integer(), nullable=True),
    sa.Column('passwd', sa.Text(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('login_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Point')
    # ### end Alembic commands ###
