"""empty message

Revision ID: d19fe365bb1e
Revises: af6407bfa0c9
Create Date: 2023-07-21 19:15:13.053100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19fe365bb1e'
down_revision = 'af6407bfa0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('stid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('school', sa.Text(), nullable=False),
    sa.Column('local', sa.Text(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school'], ['student.stid'], ),
    sa.ForeignKeyConstraint(['stid'], ['student.stid'], ),
    sa.PrimaryKeyConstraint('stid', 'school'),
    sa.UniqueConstraint('stid', 'school', name='pk_stid_school_point')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    # ### end Alembic commands ###
