"""empty message

Revision ID: e64a8f481bc2
Revises: 80201929bfc7
Create Date: 2023-07-24 15:40:46.319488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64a8f481bc2'
down_revision = '80201929bfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.alter_column('point',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('stid')
        batch_op.drop_column('school')
        batch_op.drop_column('name')
        batch_op.drop_column('local')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('belong', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rival_id', sa.Integer(), nullable=True))
        batch_op.alter_column('local',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('passwd',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('rival')
        batch_op.drop_column('school')
        batch_op.drop_column('rival_school')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rival_school', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('school', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rival', sa.INTEGER(), nullable=True))
        batch_op.alter_column('passwd',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('local',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('rival_id')
        batch_op.drop_column('belong')

    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('school', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('stid', sa.INTEGER(), nullable=True))
        batch_op.alter_column('point',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
